In [1]:
import tensorflow as tf

In [4]:
a = tf.random.normal([4, 2, 8], mean=0, stddev=1)
tf.gather(a, axis=0, indices=[2,1,3,0])

<tf.Tensor: shape=(4, 2, 8), dtype=float32, numpy=
array([[[-0.09615768,  3.295323  ,  0.00899683, -0.87723917,
         -1.4145297 , -0.59084123,  0.41911137, -0.6555908 ],
        [-2.22081   , -1.3593057 , -3.0294626 ,  0.09535949,
          0.02993084, -1.2286209 , -0.60894644,  0.9551046 ]],

       [[ 1.2546848 ,  1.1648511 ,  1.4246484 ,  0.9783808 ,
          0.89395785, -0.77934414, -0.07325897,  1.2565767 ],
        [-0.05330878,  2.4122078 ,  1.2878345 , -0.30947873,
          0.6921606 , -1.3172921 , -1.344153  , -0.41788924]],

       [[ 0.99165183, -1.0456536 ,  1.8763175 ,  0.24732395,
          0.571229  , -0.22126554, -0.14884673, -0.1620656 ],
        [-0.8114379 ,  0.41100332, -0.7240256 ,  0.5990775 ,
         -1.0678858 ,  0.78379965, -0.4289783 , -1.6510634 ]],

       [[ 0.3526169 , -0.69115835, -0.7728591 ,  1.3188455 ,
         -0.08420042, -0.02175181, -0.31259757,  0.8368241 ],
        [ 0.31097552,  1.8166876 , -1.0708072 , -0.6312652 ,
         -0.5355094 ,

In [5]:
a

<tf.Tensor: shape=(4, 2, 8), dtype=float32, numpy=
array([[[ 0.3526169 , -0.69115835, -0.7728591 ,  1.3188455 ,
         -0.08420042, -0.02175181, -0.31259757,  0.8368241 ],
        [ 0.31097552,  1.8166876 , -1.0708072 , -0.6312652 ,
         -0.5355094 , -0.6423099 , -2.3738804 , -0.3732734 ]],

       [[ 1.2546848 ,  1.1648511 ,  1.4246484 ,  0.9783808 ,
          0.89395785, -0.77934414, -0.07325897,  1.2565767 ],
        [-0.05330878,  2.4122078 ,  1.2878345 , -0.30947873,
          0.6921606 , -1.3172921 , -1.344153  , -0.41788924]],

       [[-0.09615768,  3.295323  ,  0.00899683, -0.87723917,
         -1.4145297 , -0.59084123,  0.41911137, -0.6555908 ],
        [-2.22081   , -1.3593057 , -3.0294626 ,  0.09535949,
          0.02993084, -1.2286209 , -0.60894644,  0.9551046 ]],

       [[ 0.99165183, -1.0456536 ,  1.8763175 ,  0.24732395,
          0.571229  , -0.22126554, -0.14884673, -0.1620656 ],
        [-0.8114379 ,  0.41100332, -0.7240256 ,  0.5990775 ,
         -1.0678858 ,

In [6]:
a = tf.random.uniform([4,35,8], minval=0, maxval=100)
a.shape

TensorShape([4, 35, 8])

In [8]:
tf.gather_nd(a, [[0]]).shape

TensorShape([1, 35, 8])

In [9]:
tf.gather_nd(a, [0]).shape

TensorShape([35, 8])

In [11]:
tf.gather_nd(a, [[0,2],[0,1]]).shape

TensorShape([2, 8])

In [12]:
tf.gather_nd(a, [[0],[2]]).shape

TensorShape([2, 35, 8])

In [13]:
tf.gather_nd(a, [[[0]],[[1]]]).shape

TensorShape([2, 1, 35, 8])

In [14]:
a = tf.random.uniform([4,28,28,3],minval=0, maxval=255)
a.shape

TensorShape([4, 28, 28, 3])

In [18]:
tf.boolean_mask(a, mask=[True, False, True, False]).shape

TensorShape([2, 28, 28, 3])

In [19]:
tf.boolean_mask(a, mask=[True, True, False], axis=3).shape

TensorShape([4, 28, 28, 2])

In [20]:
a = tf.ones([2,3,4])
tf.boolean_mask(a, mask=[[True, False, False], [False, True, False]]).shape

TensorShape([2, 4])

创建tensor、索引与切片、维度变换、broadcast;

convert_to_tensor, ones, zeros, tf.random.uniform, tf.random.normal,

a[], :, ::, ::-1 ,

tf.gather, tf.gather_nd, tf.boolean_mask

shape, ndim, reshape, expand_dims, squeeze, transpose,

broadcast_to,



In [21]:
a = tf.random.normal([4,28,28,3])
a.shape, a.ndim

(TensorShape([4, 28, 28, 3]), 4)

In [22]:
tf.reshape(a, [4,784,3]).shape

TensorShape([4, 784, 3])

In [25]:
tf.reshape(a, [4,-1,3]).shape

TensorShape([4, 784, 3])

In [26]:
tf.reshape(a, [4, -1]).shape

TensorShape([4, 2352])

In [27]:
tf.reshape(a, [4, 784*3]).shape

TensorShape([4, 2352])

In [30]:
tf.reshape(a, [4, -1,4]).shape

TensorShape([4, 588, 4])

In [31]:
a = tf.random.normal([4,3,2,1])
a.shape

TensorShape([4, 3, 2, 1])

In [32]:
tf.transpose(a).shape

TensorShape([1, 2, 3, 4])

In [33]:
tf.transpose(a, perm=[0,1,3,2]).shape

TensorShape([4, 3, 1, 2])

In [2]:
a = tf.random.normal([4,35,8])

2022-04-29 19:55:47.625170: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
tf.expand_dims(a, axis=0).shape

TensorShape([1, 4, 35, 8])

In [4]:

tf.squeeze(tf.zeros([1,2,1,1,3]))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [5]:
a = tf.zeros([1,2,1,3])
tf.squeeze(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
tf.squeeze(a, axis=2)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [7]:
tf.squeeze(a, axis=1)

InvalidArgumentError: Can not squeeze dim[1], expected a dimension of 1, got 2 [Op:Squeeze]

In [8]:
 x = tf.random.normal([4,32,32,3])

In [9]:
(x + tf.random.normal([3])).shape

TensorShape([4, 32, 32, 3])

In [11]:
b = tf.broadcast_to(tf.random.normal([4,1,1,1]), [4,32,32,3])

In [12]:
b.shape

TensorShape([4, 32, 32, 3])

In [13]:
 a = tf.ones([3,4])
 a1 = tf.broadcast_to(a, [2,3,4])

In [14]:
a1

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [15]:
a2 = tf.expand_dims(a, axis=0)
a2

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [16]:
a2 = tf.tile(a2, [2,1,1])
a2


<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [17]:
# 数学运算

In [19]:
tf.math.log(8.)/tf.math.log(2.)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [21]:
a = tf.fill([2,2],2.)
b = a

In [22]:
a@b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [23]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [24]:
a = tf.ones([4,2,3])
b = tf.ones([3,5])

In [25]:
bb = tf.broadcast_to(b, [4,3,5])

In [26]:
a @ bb

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]], dtype=float32)>

In [27]:
a @ b

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]], dtype=float32)>