In [1]:
import tensorflow as tf

In [2]:
with tf.device("cpu"):
    a = tf.constant([1])

2022-04-27 16:10:30.596781: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
with tf.device("gpu"):
    b = tf.range(4)

In [4]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [5]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [6]:
b.numpy()

array([0, 1, 2, 3], dtype=int32)

In [7]:
b.ndim

1

In [8]:
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [9]:
tf.rank(tf.ones([2,2,2]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [10]:
b.name

AttributeError: Tensor.name is meaningless when eager execution is enabled.

In [11]:
b.shape

TensorShape([4])

In [12]:
tf.is_tensor(b)

True

In [13]:
b.dtype

tf.int32

In [14]:
import numpy as np
a = np.arange(5)

In [15]:
aa = tf.convert_to_tensor(a, dtype=tf.int32)
aa

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [16]:
tf.cast(aa, dtype=tf.float32)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [17]:
b = tf.constant([0,1])
bb = tf.cast(b, dtype=tf.bool)
bb

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

In [18]:
a = tf.range(5)
b = tf.Variable(a)
b.dtype
b.name


'Variable:0'

In [19]:
isinstance(b, tf.Tensor)

False

In [20]:
tf.is_tensor(b)

True

In [21]:
isinstance(b, tf.Variable)

True

In [22]:
tf.fill([2,2], 0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [23]:
tf.random.normal([2,2], mean=1, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.84262836, -0.86006486],
       [ 3.646334  , -0.43252254]], dtype=float32)>

In [24]:
tf.random.truncated_normal([2,2], mean=0, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.47784543,  0.0819713 ],
       [-0.3970247 ,  0.17930828]], dtype=float32)>

In [26]:
tf.random.uniform([2,2], minval=0, maxval=200)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[44.866467, 80.093956],
       [27.19109 , 90.69736 ]], dtype=float32)>

In [28]:
idx = tf.range(10)
idx = tf.random.shuffle(idx)
idx

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([6, 4, 1, 9, 0, 3, 7, 5, 2, 8], dtype=int32)>

In [29]:
a = tf.random.normal([10, 784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([4, 9, 0, 7, 4, 1, 9, 9, 2, 3], dtype=int32)>

In [30]:
a = tf.gather(a, idx)
b = tf.gather(b, idx)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 4, 9, 3, 4, 7, 9, 1, 0, 2], dtype=int32)>

In [31]:
x = tf.random.uniform([4,10])
y = tf.range(4)
y = tf.one_hot(y, depth=10)
y

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [32]:
loss = tf.losses.mse(y, x)
loss

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.37316224, 0.47690254, 0.1951038 , 0.22647586], dtype=float32)>

In [33]:
 tf.reduce_mean(loss)

<tf.Tensor: shape=(), dtype=float32, numpy=0.31791112>

In [34]:
tf.reduce_max(loss)

<tf.Tensor: shape=(), dtype=float32, numpy=0.47690254>

In [35]:
import tensorflow.keras.layers as layers
net = layers.Dense(10)
net.build((4,8))
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[ 0.2560985 , -0.47130007, -0.21836492, -0.23971513, -0.1645943 ,
        -0.3124841 , -0.4224923 , -0.42203927, -0.26106152, -0.41792876],
       [-0.36025986,  0.4091013 ,  0.09655392,  0.06125951,  0.2893207 ,
         0.29439414, -0.49606788,  0.3969766 , -0.18062484,  0.57656157],
       [-0.12936321, -0.45882833, -0.34119478,  0.09357572, -0.44086498,
         0.2509519 ,  0.1894769 , -0.31860968, -0.45407715, -0.1696012 ],
       [-0.38193673, -0.31470245, -0.5710949 , -0.27514416, -0.41926426,
         0.02106792,  0.4858507 , -0.54304624, -0.16853455,  0.23771107],
       [ 0.46919143,  0.5427618 ,  0.5173875 ,  0.1646254 , -0.56983715,
         0.21908742,  0.15927666,  0.00796187, -0.33848375,  0.06156087],
       [ 0.11625457, -0.318684  , -0.34059215,  0.0686605 ,  0.12725455,
         0.46057606, -0.47211412,  0.07354802, -0.33442372,  0.12601113],
       [-0.5591002 ,  0.38597953, -0.26882902,  0.30756044

In [36]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [37]:
x = tf.random.normal([4,784])
x

<tf.Tensor: shape=(4, 784), dtype=float32, numpy=
array([[-1.0446228 ,  0.05430403, -0.5051472 , ...,  0.22594926,
         0.28312528,  0.2057791 ],
       [-0.6669609 , -0.64986604, -0.6028532 , ...,  0.92446035,
         0.31271875, -1.4145143 ],
       [ 0.95424646, -1.1847402 , -1.4734404 , ...,  0.538277  ,
        -1.5485902 , -0.18081056],
       [ 0.6945637 , -0.06869905,  1.1719948 , ..., -0.275786  ,
         0.21236877,  0.8309715 ]], dtype=float32)>

In [38]:
net = layers.Dense(10)
net.build((4,784))
net(x).shape

TensorShape([4, 10])

In [39]:
net.kernel.shape

TensorShape([784, 10])

In [40]:
net.bias.shape

TensorShape([10])

In [41]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=10000)


17473536/17464789 [==============================] - 2s 0us/step


In [42]:
X_train = tf.keras.preprocessing.sequence.pad_sequences(X_train, maxlen=80)
X_train.shape

(25000, 80)

In [45]:
embedding = layers.Embedding(10000, 100)
emb = embedding(X_train)
emb.shape

TensorShape([25000, 80, 100])

In [46]:
X_train

array([[  15,  256,    4, ...,   19,  178,   32],
       [ 125,   68,    2, ...,   16,  145,   95],
       [ 645,  662,    8, ...,    7,  129,  113],
       ...,
       [ 529,  443,    2, ...,    4, 3586,    2],
       [ 286, 1814,   23, ...,   12,    9,   23],
       [  97,   90,   35, ...,  204,  131,    9]], dtype=int32)

In [47]:
type(X_train)

numpy.ndarray

In [48]:
emb

<tf.Tensor: shape=(25000, 80, 100), dtype=float32, numpy=
array([[[-0.03549545,  0.01698314,  0.03793411, ..., -0.03077124,
         -0.02482761, -0.00470507],
        [-0.01821282,  0.04480853, -0.01568804, ..., -0.04572067,
          0.00136788,  0.04071904],
        [-0.00303494,  0.03200689, -0.04318218, ..., -0.00289723,
         -0.01359586, -0.00253434],
        ...,
        [ 0.02997302, -0.00899875,  0.04301487, ...,  0.02587506,
         -0.02537811,  0.03906636],
        [ 0.00479629,  0.02998481, -0.00722818, ...,  0.01538411,
          0.00922582,  0.00686264],
        [ 0.01168407,  0.02245698,  0.04585085, ..., -0.04423083,
         -0.01911763,  0.01058823]],

       [[-0.04790763,  0.04118916,  0.04989732, ...,  0.04893322,
          0.02498287, -0.02169211],
        [-0.03103827,  0.00907803,  0.04001968, ...,  0.00279223,
          0.04143609, -0.02299179],
        [-0.03622925,  0.00261127, -0.00645547, ..., -0.02466977,
         -0.01216389, -0.01276566],
        .

In [49]:
emb[:4]

<tf.Tensor: shape=(4, 80, 100), dtype=float32, numpy=
array([[[-0.03549545,  0.01698314,  0.03793411, ..., -0.03077124,
         -0.02482761, -0.00470507],
        [-0.01821282,  0.04480853, -0.01568804, ..., -0.04572067,
          0.00136788,  0.04071904],
        [-0.00303494,  0.03200689, -0.04318218, ..., -0.00289723,
         -0.01359586, -0.00253434],
        ...,
        [ 0.02997302, -0.00899875,  0.04301487, ...,  0.02587506,
         -0.02537811,  0.03906636],
        [ 0.00479629,  0.02998481, -0.00722818, ...,  0.01538411,
          0.00922582,  0.00686264],
        [ 0.01168407,  0.02245698,  0.04585085, ..., -0.04423083,
         -0.01911763,  0.01058823]],

       [[-0.04790763,  0.04118916,  0.04989732, ...,  0.04893322,
          0.02498287, -0.02169211],
        [-0.03103827,  0.00907803,  0.04001968, ...,  0.00279223,
          0.04143609, -0.02299179],
        [-0.03622925,  0.00261127, -0.00645547, ..., -0.02466977,
         -0.01216389, -0.01276566],
        ...,


In [54]:
rnn = layers.SimpleRNN(256)
out = rnn(emb[:4])
out

<tf.Tensor: shape=(4, 256), dtype=float32, numpy=
array([[ 0.09489315,  0.00530183, -0.05403531, ..., -0.26488936,
        -0.08648812, -0.06432852],
       [-0.20160827, -0.11631009,  0.13095579, ...,  0.07085965,
         0.01271516, -0.00695578],
       [ 0.0725302 ,  0.06075795,  0.0866219 , ..., -0.21874519,
         0.00166563,  0.06918591],
       [ 0.15150765, -0.16449487, -0.02146837, ...,  0.03766637,
         0.15902916,  0.18900436]], dtype=float32)>

In [56]:
x = tf.random.normal((4, 32,32,3))
net = layers.Conv2D(16, kernel_size=3)
net(x)

<tf.Tensor: shape=(4, 30, 30, 16), dtype=float32, numpy=
array([[[[ 6.85402572e-01,  5.20326793e-01, -5.88445589e-02, ...,
           2.57830352e-01,  2.53431141e-01, -7.05935061e-01],
         [ 4.46757168e-01, -6.21496081e-01,  2.70653307e-01, ...,
           1.28026053e-01,  1.46189332e-01, -7.02892900e-01],
         [ 2.86261559e-01, -3.38881910e-01,  6.76926196e-01, ...,
           9.34149846e-02, -2.67320156e-01,  9.62250605e-02],
         ...,
         [-2.24887669e-01,  9.59975898e-01,  1.47894591e-01, ...,
           5.76732516e-01, -5.49984217e-01, -2.41283983e-01],
         [ 2.74794787e-01, -4.72101092e-01, -4.98782009e-01, ...,
           6.98703885e-01,  7.48319924e-01,  6.38418317e-01],
         [ 4.66267079e-01,  1.37359664e-01, -2.13428915e-01, ...,
          -9.19995233e-02,  1.89875718e-02, -1.62729278e-01]],

        [[-1.23679534e-01, -4.64243323e-01, -1.91501155e-01, ...,
          -4.48446631e-01,  3.60000908e-01, -3.34385425e-01],
         [ 1.02999556e+00, -3.1